"""empty message

Revision ID: 19a0d7816315
Revises: 458d90f4147
Create Date: 2015-01-09 15:51:11.651983

"""

# revision identifiers, used by Alembic.
revision = '19a0d7816315'
down_revision = '458d90f4147'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exif_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(length=50), nullable=True),
    sa.Column('camera_model', sa.String(length=50), nullable=True),
    sa.Column('orientarion', sa.Integer(), nullable=True),
    sa.Column('focal_length', sa.String(length=20), nullable=True),
    sa.Column('aperture', sa.String(length=20), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['photo'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exif_data')
    ### end Alembic commands ###
