"""empty message

Revision ID: 1dcc6f1e30d1
Revises: 3995f75be7b9
Create Date: 2015-01-11 12:39:41.263599

"""

# revision identifiers, used by Alembic.
revision = '1dcc6f1e30d1'
down_revision = '3995f75be7b9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exif_data')
    op.drop_table('photo')
    op.drop_table('directory')
    op.drop_table('album')
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('timestamp_from', sa.DateTime(), nullable=True),
    sa.Column('timestamp_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('album', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('directory', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=5), nullable=True),
    sa.Column('mode', sa.String(length=5), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['directory'], ['directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_path'), 'photo', ['path'], unique=False)
    op.create_table('exif_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('camera_make', sa.String(length=50), nullable=True),
    sa.Column('camera_model', sa.String(length=50), nullable=True),
    sa.Column('orientarion', sa.Integer(), nullable=True),
    sa.Column('focal_length', sa.String(length=20), nullable=True),
    sa.Column('aperture', sa.String(length=20), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['photo'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exif_data')
    op.drop_table('photo')
    op.drop_table('directory')
    op.drop_table('album')
    ### end Alembic commands ###
