"""empty message

Revision ID: 30ddd12c616c
Revises: 1dcc6f1e30d1
Create Date: 2015-01-21 15:50:27.117031

"""

# revision identifiers, used by Alembic.
revision = '30ddd12c616c'
down_revision = '1dcc6f1e30d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('photo', sa.Column('is_hidden', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'is_hidden')
    op.drop_column('album', 'is_hidden')
    ### end Alembic commands ###
