"""empty message

Revision ID: 458d90f4147
Revises: 4431a41e9dbd
Create Date: 2015-01-08 16:13:13.570855

"""

# revision identifiers, used by Alembic.
revision = '458d90f4147'
down_revision = '4431a41e9dbd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('format', sa.String(length=5), nullable=True))
    op.add_column('photo', sa.Column('mode', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'mode')
    op.drop_column('photo', 'format')
    ### end Alembic commands ###
