"""empty message

Revision ID: aca284e520b
Revises: f4ffb386026
Create Date: 2015-02-05 17:30:53.441486

"""

# revision identifiers, used by Alembic.
revision = 'aca284e520b'
down_revision = 'f4ffb386026'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'album', 'album', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    ### end Alembic commands ###
