"""empty message

Revision ID: f4ffb386026
Revises: 30ddd12c616c
Create Date: 2015-01-23 18:37:05.167498

"""

# revision identifiers, used by Alembic.
revision = 'f4ffb386026'
down_revision = '30ddd12c616c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    ### end Alembic commands ###
